# PowerShell script to generate SQL INSERT statements with hashed passwords
# Usage: .\generate_sample_users.ps1
# Requires: WSL or Linux environment with compiled test_hash_password

param(
    [string]$WSLPath = "wsl"
)

$ErrorActionPreference = "Stop"

# Define sample users: username, password
$sampleUsers = @(
    @{Username = "alice"; Password = "alice123"},
    @{Username = "bob"; Password = "bob123"},
    @{Username = "charlie"; Password = "charlie123"},
    @{Username = "testuser1"; Password = "testpass1"},
    @{Username = "testuser2"; Password = "testpass2"},
    @{Username = "testuser3"; Password = "testpass3"}
)

Write-Host "=== Generating SQL INSERT statements with hashed passwords ===" -ForegroundColor Cyan
Write-Host ""

# Check if test_hash_password exists (try WSL first since we're on Windows)
$useWSL = $true

# Generate hashes
$hashes = @()
foreach ($user in $sampleUsers) {
    Write-Host "Hashing password for $($user.Username)..." -ForegroundColor Yellow
    
    # Use WSL to run the tool
    $hashOutput = & $WSLPath -e bash -c "cd /mnt/e/GitHub_Class_project/LTM_Group04/server && ./build/test_hash_password '$($user.Password)'" 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Error generating hash for $($user.Username): $hashOutput" -ForegroundColor Red
        exit 1
    }
    $hash = ($hashOutput | Select-Object -Last 1).Trim()
    
    $hashes += @{
        Username = $user.Username
        Password = $user.Password
        Hash = $hash
    }
    
    Write-Host "  Generated hash: $hash" -ForegroundColor Green
}

Write-Host ""
Write-Host "=== SQL INSERT statements ===" -ForegroundColor Cyan
Write-Host ""

# Generate SQL
$nl = [Environment]::NewLine
$sql = "-- =========================" + $nl
$sql += "-- SAMPLE USERS (with hashed passwords)" + $nl
$sql += "-- =========================" + $nl
$sql += "-- Generated by generate_sample_users.ps1" + $nl
$sql += "-- Passwords are hashed using SHA256 + salt (format: salt`$hash)" + $nl
$sql += $nl
$sql += "INSERT INTO users (username, password) VALUES" + $nl

for ($i = 0; $i -lt $hashes.Length; $i++) {
    $hash = $hashes[$i]
    if ($i -eq $hashes.Length - 1) {
        $sql += "('$($hash.Username)', '$($hash.Hash)');" + $nl
    } else {
        $sql += "('$($hash.Username)', '$($hash.Hash)')," + $nl
    }
}

Write-Host $sql
Write-Host ""
Write-Host "=== SQL output ===" -ForegroundColor Cyan
Write-Host "Copy the SQL above and add it to db.sql" -ForegroundColor Yellow

# Also write to a file
$outputFile = "sample_users.sql"
$sql | Out-File -FilePath $outputFile -Encoding UTF8
Write-Host "SQL also written to: $outputFile" -ForegroundColor Green
